name: Cypress Cucumber Tests

on:
  push:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

 #   - name: Run Cypress Cucumber Tests in Chrome
  #    run: npx cypress run --spec cypress/integration/*/**/.feature" --browser chrome

    # ARRIBA: EJECUTO TODOS LOS TEST.
    # ABAJO EJECUTO DE A 1 TEST INDIVIDUAL.  

    - name: Run Cypress Cucumber Test in Chrome
      run: npx cypress run --spec cypress\integration\*\**\Auditor_8.feature --browser chrome
  #    run: npx cypress run --spec cypress/integration/*/**/Auditor_2.feature --browser chrome